name: Index Blogger Posts

on:
  # Run daily at 2 AM UTC
  schedule:
    - cron: '0 2 * * *'
  
  # Allow manual trigger
  workflow_dispatch:
    inputs:
      force_reindex:
        description: 'Force reindex all URLs'
        required: false
        type: boolean
        default: false

jobs:
  index-posts:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Decode service account key
      env:
        SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
      run: |
        echo "$SERVICE_ACCOUNT_KEY" | base64 -d > service-account-key.json
        
    - name: Run indexing script
      env:
        GOOGLE_APPLICATION_CREDENTIALS: service-account-key.json
        BLOGGER_RSS_FEED: ${{ vars.BLOGGER_RSS_FEED }}
        BLOG_URL: ${{ vars.BLOG_URL }}
        MAX_REQUESTS_PER_DAY: ${{ vars.MAX_REQUESTS_PER_DAY }}
        FORCE_REINDEX: ${{ inputs.force_reindex }}
      run: |
        python src/indexer.py
        
    - name: Upload logs
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: indexing-logs
        path: logs/
        retention-days: 30
        
    - name: Clean up
      if: always()
      run: |
        rm -f service-account-key.json
